'\" t
.\"     Title: miktex-mf
.\"    Author: Christian Schenk
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: May 13, 2026
.\"    Manual: User Commands
.\"    Source: MiKTeX 26.5
.\"  Language: English
.\"
.TH "MIKTEX\-MF" "1" "May 13, 2026" "MiKTeX 26\&.5" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
miktex-mf \- METAFONT, a language for font and logo design
.SH "SYNOPSIS"
.HP \w'\fBmiktex\-mf\fR\ 'u
\fBmiktex\-mf\fR [\fIoption\fR...] [[\fIcommand\fR...] | [\fIfile\fR]]
.SH "DESCRIPTION"
.PP
This man page is an adaption of the corresponding
TeX Live
man page\&.
.PP
METAFONT
reads the program in the specified files and outputs font rasters (in
GF
format) and font metrics (in
TFM
format)\&. The
METAFONT
language is described in
The METAFONTbook\&.
.PP
Like
TeX,
METAFONT
is normally used with a large body of precompiled macros, and font generation in particular requires the support of several macro files\&. This version of
METAFONT
looks at its command line to see what name it was called under\&. Both
\fBinimf\fR
and
\fBvirmf\fR
are links to the
\fBmiktex\-mf\fR
executable\&. When called as
\fBinimf\fR
(or when the
\fB\-\-initialize\fR
option is given) it can be used to precompile macros into a
\&.base
file\&. When called as
\fBvirmf\fR
it will use the
\fIplain\fR
base\&. When called under any other name,
METAFONT
will use that name as the name of the base to use\&. For example, when called as
\fBmiktex\-mf\fR
the
\fImf\fR
base is used, which is identical to the
\fIplain\fR
base\&. Other bases than
\fIplain\fR
are rarely used\&.
.PP
The commands given on the command line to the
METAFONT
program are passed to it as the first input line\&. (But it is often easier to type extended arguments as the first input line, since shells tend to gobble up or misinterpret
METAFONT\*(Aqs favorite symbols, like semicolons, unless you quote them\&.) As described in
The METAFONTbook, that first line should begin with a filename, a
\fB\econtrolsequence\fR, or a
&\fIbasename\fR\&.
.PP
The normal usage is to say
\fBmiktex\-mf \emode=\fR\fB\fIprintengine\fR\fR\fB; input \fR\fB\fIfont\fR\fR
to start processing
\fIfont\fR\&.mf\&. (Or you can just say
\fBmiktex\-mf\fR
and give the other stuff on the next line\&.) Other control sequences, such as
\fBbatchmode\fR
(for silent operation) can also appear\&. The name
\fIfont\fR
will be the
\(lqjobname\(rq, and is used in forming output file names\&. If
METAFONT
doesn\*(Aqt get a file name in the first line, the job name is
mfput\&. The default extension,
\&.mf, can be overridden by specifying an extension explicitly\&.
.PP
A log of error messages goes into the file
\fIjobname\fR\&.log\&. The output files are
\fIjobname\fR\&.tfm
and
\fIjobname\fR\&.\fInumber\fRgf, where
\fInumber\fR
depends on the resolution and magnification of the font\&. The mode in this example is shown generically as
\fIprintengine\fR, a symbolic term for which the name of an actual device or, most commonly, the name
localfont
(see below) must be substituted\&. If the mode is not specified or is not valid,
METAFONT
will default to proof mode which produces large character images for use in font design and refinement\&. Proof mode can be recognized by the suffix
\&.2602gf
after the job name\&. Examples of proof mode output can be found in
Computer Modern Typefaces
(Volume\ \&E of Computers and Typesetting)\&. The system of magsteps is identical to the system used by
TeX, with values generally in the range 0\&.5, 1\&.0, 2\&.0, 3\&.0, 4\&.0 and 5\&.0\&.
.PP
Magnification can also be specified not as a magstep but as an arbitrary value, such as 1\&.315, to create special character sizes\&.
.PP
Before font production can begin, it is necessary to set up the appropriate base files\&. The minimum set of components for font production for a given printengine is the
plain\&.mf
macro file and the local
\fBmode_def\fR
file\&. The macros in
plain\&.mf
can be studied in an appendix to
The METAFONTbook; they were developed by Donald\ \&E\&. Knuth, and this file should never be altered except when it is officially upgraded\&. Each
\fBmode_def\fR
specification helps adapt fonts to a particular printengine\&. The local ones in use on this
.\" modes.mf
computer should be in
modes\&.mf\&.
.PP
The
\fBe\fR
response to
METAFONT\*(Aqs error\-recovery prompt causes the default editor to start up at the current line of the current file\&. The configuration value
\fI[Core]Editor\fR
can be used to change the editor used\&. It may contain a string with
%f
indicating where the file name goes and
%l
indicating where the decimal line number (if any) goes\&. For example, an
\fI[Core]Editor\fR
string for
\fBemacs\fR
can be set with the command
.sp
.if n \{\
.RS 4
.\}
.nf
> \fBinitexmf \-\-set\-config\-value="[Core]Editor=emacs +%l%f"\fR
.fi
.if n \{\
.RE
.\}
.PP
A convenient file is
null\&.mf, containing nothing\&. When
METAFONT
can\*(Aqt find the file it thinks you want to input, it keeps asking you for another file name; responding
\fBnull\fR
gets you out of the loop if you don\*(Aqt want to input anything\&.
.SH "ONLINE GRAPHICS OUTPUT"
.PP
You can see
METAFONTs output without printing\&. Chapter\ \&23 of
The METAFONTbook
describes what you can do\&. You enable screen ouput by giving
\fB\-\-screen\fR
on the command\-line\&.
.SH "OPTIONS"
.PP
\fB\-\-alias=\fR\fB\fIname\fR\fR
.RS 4
Pretend to be program
\fIname\fR, i\&.e\&., set program (and memory dump) name to
\fIname\fR\&.
.\" --alias=name
This may affect the search paths and other values used\&. Using this option is equivalent to copying the program file to
\fIname\fR
and invoking
\fIname\fR\&.
.RE
.PP
\fB\-\-aux\-directory=\fR\fB\fIdir\fR\fR
.RS 4
Set
\fIdir\fR
as the directory to which
.\" --aux-directory=dir
auxiliary files are written\&. Also look for input files in
\fIdir\fR
first, before along the normal search path\&.
.RE
.PP
\fB\-\-bistack\-size=\fR\fB\fIn\fR\fR
.RS 4
Set the
.\" --bistack-size=n
size of the stack for bisection algorithms\&.
.RE
.PP
\fB\-\-buf\-size=\fR\fB\fIn\fR\fR
.RS 4
Set the
.\" --buf-size=n
the maximum number of characters simultaneously present in current lines of open files and in control sequences between
\fB\ecsname\fR
and
\fB\eendcsname\fR\&.
TeX
uses the buffer to contain input lines, but macro expansion works by writing material into the buffer and reparsing the line\&. As a consequence, certain constructs require the buffer to be very large, even though most documents can be handled with a small value\&.
.RE
.PP
\fB\-\-c\-style\-errors\fR
.RS 4
Change the way, error messages are printed\&. The alternate style looks like error messages from many compilers and is easier to parse for some editors\&.
.\" --c-style-errors.\" --file-line-error.\" --file-line-error-style.\" error messages: C/C++ style
.RE
.PP
\fB\-\-disable\-installer\fR
.RS 4
Disable automatic installation of packages\&.
.\" --disable-installer
Specifying this option overrules settings in the
MiKTeX
configuration data store\&.
.RE
.PP
\fB\-\-dont\-parse\-first\-line\fR
.RS 4
Disable checking whether the first line of the main input file
.\" --dont-parse-first-line
starts with
\fB%&\fR\&.
.RE
.PP
\fB\-\-enable\-installer\fR
.RS 4
Enable automatic installation of packages\&.
.\" --enable-installer
Specifying this option overrules settings in the
MiKTeX
configuration data store\&.
.RE
.PP
\fB\-\-error\-line=\fR\fB\fIn\fR\fR
.RS 4
Set the width of context lines on
.\" --error-line=n.\" error messages: line width
terminal error messages\&.
.RE
.PP
\fB\-\-half\-error\-line=\fR\fB\fIn\fR\fR
.RS 4
Set the
.\" --half-error=n
width of first lines of contexts in terminal error messages\&.
.RE
.PP
\fB\-\-halt\-on\-error\fR
.RS 4
Quit after the
.\" --halt-on-error
first error\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
.\" --help
Give help and exit\&.
.RE
.PP
\fB\-\-hhelp\fR
.RS 4
.\" --hhelp
This option is only available on
Windows
systems: show the manual page in an HTML Help window and exit when the window is closed\&.
.RE
.PP
\fB\-\-include\-directory=\fR\fB\fIdir\fR\fR
.RS 4
Add the directory
\fIdir\fR
to the
.\" --include-directory=dir
head of the list of directories to be searched for input files\&.
.RE
.PP
\fB\-\-initialize\fR
.RS 4
Become the
\fIINI\fR
variant
.\" --initialize
of the program\&.
.RE
.PP
\fB\-\-interaction=\fR\fB\fImode\fR\fR
.RS 4
Set the interaction mode\&. Must be one of
\fBbatchmode\fR,
.\" --interaction=mode\fBnonstopmode\fR,
\fBscrollmode\fR
and
\fBerrorstopmode\fR\&. The meaning of these modes is the same as the corresponding commands\&.
.RE
.PP
\fB\-\-job\-name=\fR\fB\fIname\fR\fR
.RS 4
Set the name of the job (\fB\ejobname\fR)\&.
.\" --job-name=name
This has an affect on the output file names\&.
.RE
.PP
\fB\-\-job\-time=\fR\fB\fIfile\fR\fR
.RS 4
Set the time\-stamp of all output files equal to
.\" --job-time=file\fIfile\fR\*(Aqs time\-stamp\&.
.RE
.PP
\fB\-\-lig\-table\-size=\fR\fB\fIn\fR\fR
.RS 4
Set the
.\" --lib-table-size=n
maximum number of ligature/kern steps\&. Must be at least 255 and at most 32510\&.
.RE
.PP
\fB\-\-main\-memory=\fR\fB\fIn\fR\fR
.RS 4
Change the
.\" --main-memory=n
total size (in memory words) of the main memory array\&. Relevant only while creating memory dump files\&.
.RE
.PP
\fB\-\-max\-print\-line=\fR\fB\fIn\fR\fR
.RS 4
Set the
.\" --max-print-line=n
width of longest text lines output; should be at least
60\&.
.RE
.PP
\fB\-\-max\-strings=\fR\fB\fIn\fR\fR
.RS 4
Set the
.\" --max-strings=n
maximum number of strings\&.
.RE
.PP
\fB\-\-max\-wiggle=\fR\fB\fIn\fR\fR
.RS 4
Set the
.\" --max-wiggle=n
number of autorounded points per cycle\&.
.RE
.PP
\fB\-\-move\-size=\fR\fB\fIn\fR\fR
.RS 4
Set the
.\" --move-size=n
the space for storing moves in a single octant\&.
.RE
.PP
\fB\-\-no\-c\-style\-errors\fR
.RS 4
Don\*(Aqt change the way, error messages are printed\&.
.\" --no-c-style-errors.\" --no-file-line-error.\" --no-file-line-error-style
.RE
.PP
\fB\-\-output\-directory=\fR\fB\fIdir\fR\fR
.RS 4
Write output files in
\fIdir\fR\&.
.\" --output-directory=dir
instead of the current directory\&. Look up input files in
\fIdir\fR
first, then along the normal search path\&.
.RE
.PP
\fB\-\-param\-size=\fR\fB\fIn\fR\fR
.RS 4
Set the
.\" --param-size=n
the maximum number of simultaneous macro parameters\&.
.RE
.PP
\fB\-\-parse\-first\-line\fR
.RS 4
Check whether the first line of the main input file starts with
\fB%&\fR, and parse if it does\&.
.\" --parse-first-line
This can be used to specify extra command\-line options\&.
.RE
.PP
\fB\-\-path\-size=\fR\fB\fIn\fR\fR
.RS 4
Set the
.\" --path-size=n
the maximum number of knots between breakpoints of a path\&.
.RE
.PP
\fB\-\-pool\-size=\fR\fB\fIn\fR\fR
.RS 4
Set the
.\" --pool-size=n
maximum number of characters in strings, including all error messages and help texts, and the names of all fonts and control sequences\&.
.RE
.PP
\fB\-\-quiet\fR
.RS 4
.\" --quiet
Suppress all output, except errors\&.
.RE
.PP
\fB\-\-record\-package\-usages=\fR\fB\fIfile\fR\fR
.RS 4
Record all package usages and write
.\" --record-package-usages=file
them into
\fIfile\fR\&.
.RE
.PP
\fB\-\-recorder\fR
.RS 4
Enable the file name recorder\&. This leaves a trace of the files opened for input and output in a file
.\" --recorder
with the extension
\&.fls\&.
.RE
.PP
\fB\-\-screen\fR
.RS 4
.\" --screen
Enable screen output\&.
.RE
.PP
\fB\-\-stack\-size=\fR\fB\fIn\fR\fR
.RS 4
Set the maximum number of
.\" --stack-size=n
simultaneous input sources\&.
.RE
.PP
\fB\-\-string\-vacancies=\fR\fB\fIn\fR\fR
.RS 4
Set the minimum
.\" --string-vacancies=n
number of characters that should be available for the user\*(Aqs control sequences and font names, after the compiler\*(Aqs own error messages are stored\&. Must be at least 25000 less than
\fIpool_size\fR, but doesn\*(Aqt need to be nearly that large\&.
.RE
.PP
\fB\-\-tcx=\fR\fB\fItcxname\fR\fR
.RS 4
.\" --tcx=tcxname
.\" --translate-file=tcxname
Use the
\fItcxname\fR
translation table to set the mapping of input characters and re\-mapping of output characters\&.
.RE
.PP
\fB\-\-time\-statistics\fR
.RS 4
Show processing
.\" --time-statistics
time statistics\&.
.RE
.PP
\fB\-\-trace\fR\fB[=\fItracestreams\fR]\fR
.RS 4
Enable trace messages\&.
.\" --trace=tracestreams
The
\fItracestreams\fR
argument, if specified, is a comma\-separated list of trace stream names (Chapter\ \&9, Trace Streams)\&.
.RE
.PP
\fB\-\-undump=\fR\fB\fIname\fR\fR
.RS 4
Use
\fIname\fR
as the name of the format to
.\" --undump=name
be used, instead of the name by which the program was called or a
.sp
.if n \{\
.RS 4
.\}
.nf
%&
.fi
.if n \{\
.RE
.\}
.sp
line\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
.\" --version
Show version information and exit\&.
.RE
.SH "ENVIRONMENT"
.PP
\fBMFINPUTS\fR
.RS 4
.\" MFINPUTS
Extra paths to locate
METAFONT\fBinput\fR
and
\fBopenin\fR
files\&.
.RE
.PP
\fBMIKTEX_EDITOR\fR
.RS 4
.\" MIKTEX_EDITOR
The editor to use when selecting
\fBe\fR
in the error prompt menu\&.
.sp
The value can contain these placesholder:
.PP
\fB%f\fR
.RS 4
The name of the file, which contains the erroneous line of
TeX
code\&.
.RE
.PP
\fB%l\fR
.RS 4
The line number\&.
.RE
.RE
.PP
\fBMIKTEX_TRACE\fR
.RS 4
.\" MIKTEX_TRACE
Comma\-separated list of trace stream names (see
Chapter\ \&9, Trace Streams)\&. If this variable is set, then
MiKTeX
programs will write trace messages into the configured log sink\&.
.RE
.SH "SEE ALSO"

978-0201134452. The METAFONTbook. Donald E\&. Knuth. Addison-Wesley. 1986. 

